In [1]:
import pandas as pd

In [2]:
### TASK 1

In [4]:
data = {
      'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
      'Age': [24, 27, 22, 32, 29],
      'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
      'Salary': [45000, 54000, 50000, 62000, 47000]
  }
df = pd.DataFrame(data)

In [5]:
df.head(5)

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

In [6]:
df[['Age','Salary']].describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  51600.000000
std     3.962323   6730.527468
min    22.000000  45000.000000
25%    24.000000  47000.000000
50%    27.000000  50000.000000
75%    29.000000  54000.000000
max    32.000000  62000.000000

In [7]:
hr_avg_salary = df[df['Department'] == 'HR']['Salary'].mean()
print(hr_avg_salary)

46000.0

In [8]:
### TASK 2

In [9]:
df['Bonus'] = df['Salary'] * 0.10
print(df)

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
1      Bob   27    Finance   54000  5400.0
2  Charlie   22         IT   50000  5000.0
3    Diana   32  Marketing   62000  6200.0
4      Eve   29         HR   47000  4700.0

In [ ]:
### TASK 3

In [11]:
filtered_df = df[(df['Age'] >=25) & (df['Age'] <=30)]
print(filtered_df)

  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0

In [12]:
### TASK 4

In [15]:
average_salary = df.groupby('Department')['Salary'].mean().reset_index()
print(average_salary)

  Department   Salary
0    Finance  54000.0
1         HR  46000.0
2         IT  50000.0
3  Marketing  62000.0

In [16]:
### TASK 5

In [18]:
sorted_df = df.sort_values(by='Salary',ascending=True).reset_index()
print(sorted_df)

   index     Name  Age Department  Salary   Bonus
0      0    Alice   24         HR   45000  4500.0
1      4      Eve   29         HR   47000  4700.0
2      2  Charlie   22         IT   50000  5000.0
3      1      Bob   27    Finance   54000  5400.0
4      3    Diana   32  Marketing   62000  6200.0

In [19]:
sorted_df.to_csv('sorted_employees.csv',index=False)